# Generated by Django 5.0.3 on 2024-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
