# Generated by Django 5.0.3 on 2024-03-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_poop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poop',
        ),
    ]
