# Generated by Django 5.0.3 on 2024-03-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
