# Generated by Django 5.0.3 on 2024-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_poop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poop',
            name='id',
        ),
        migrations.AlterField(
            model_name='poop',
            name='code',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
