# Generated by Django 5.0.3 on 2024-03-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_poop_id_alter_poop_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Poop',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
