# Generated by Django 5.0.3 on 2024-03-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_admin_delete_poop_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(db_column='User_ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('middlename', models.CharField(db_column='MiddleName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
            ],
            options={
                'db_table': 'user',
                'db_table_comment': 'Table for users in website',
                'managed': False,
            },
        ),
    ]
